### ISSUE TITLE
we have some problem

### ISSUE THREAD

**Issue by Takaramono-Kami** [hawshemi/SNI-Finder#1]
![image](https://github.com/hawshemi/SNI-Finder/assets/64749378/0dd63c27-7d00-4f59-b127-28bca9a12302)

**Comment by hawshemi** [comment]
It will be fixed soon.

For now you can build yourself on linux, or use windows version

**Comment by hawshemi** [comment]
Test new version:
https://github.com/hawshemi/SNI-Finder/releases/tag/1.0.1
