### ISSUE TITLE
اجرا نمیشه روی ویندوز

### ISSUE THREAD

**Issue by Argo160** [hawshemi/SNI-Finder#3]
![Capture](https://github.com/hawshemi/SNI-Finder/assets/116899376/f8002e9b-4aa3-4fb5-aa4a-3bf52b4c578b)

**Comment by hawshemi** [comment]
روی ویندوز تست شده و بدون مشکل کار میکنه.
فایل رو در یک فولدر قرار بدید و بعد CMD یا PowerShell رو در اون فولدر باز کنید و برنامه رو ران کنید.

فولدری که برنامه داخلش هست رو باز کنید، و در محیط فولدر شیفت+راست کلیک کنید. در منو گزینه ی Open command prompt here یا گزینه ای شبیه به این مورد رو بزنید. و بعد ران کنید.

**Comment by Argo160** [comment]
فرقی نکرد. شاید روی ویندوز 7 اجرا نمیشه
![Capture](https://github.com/hawshemi/SNI-Finder/assets/116899376/a7a3a63d-3912-40a0-87ca-308fd278b081)

**Comment by hawshemi** [comment]
داخل اسم فایل مشکل وجود داشت.

لطفا این فایل رو پاک کنید و دوباره از گیتهاب دانلود کنید.

**Comment by Argo160** [comment]
چیزی آپدیت نشده
هنوز همون فایلهای 18 ساعت پیشو نشون میده
هر زمان آپدیت شد تست میکنم خبر میدم

**Comment by hawshemi** [comment]
اسم فایل رو فقط تغییر دادم.
تایم انتشار فرقی نکرده.

اسم فایل باید الان `SNI-Finder-windows-amd64.exe` باشه

**Comment by Argo160** [comment]
فقط تایتل فایل تغییر کرده و در واقع وقتی دانلود میشه همون `SNI-Finder-windows.amd64.exe` قبلی هست
دستی بعد از دانلود تغییر دادم اسمو اوکی شد
ممنون
