### ISSUE TITLE
Custom List

### ISSUE THREAD

**Issue by aliafshany** [hawshemi/SNI-Finder#4]
سلام
آیا امکان این وجود داره که لیست دامنه هارو خودمون به اسکریپت بدیم تا اسکن کنه؟
ممنون

**Comment by hawshemi** [comment]
سلام. هنوز امکانش نیست. البته از ابتدا هدف این اسکریپت این بوده که بدون لیست عمل کنه و صرفا روی رنج آیپی سرور، دامنه های مناسب SNI شدن رو پیدا کنه.
